+ python main.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/python/3.6-conda5.2/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/python/3.6-conda5.2/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python/3.6-conda5.2/lib/python3.6/concurrent/futures/process.py", line 295, in _queue_management_worker
    shutdown_worker()
  File "/usr/local/python/3.6-conda5.2/lib/python3.6/concurrent/futures/process.py", line 253, in shutdown_worker
    call_queue.put_nowait(None)
  File "/usr/local/python/3.6-conda5.2/lib/python3.6/multiprocessing/queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "/usr/local/python/3.6-conda5.2/lib/python3.6/multiprocessing/queues.py", line 83, in put
    raise Full
queue.Full

Traceback (most recent call last):
  File "main.py", line 152, in compute_alpha_i_metric_parallel
    my_callback(future.result())
  File "/usr/local/python/3.6-conda5.2/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/python/3.6-conda5.2/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 370, in <module>
    main()
  File "main.py", line 366, in main
    analyze(fileName)
  File "main.py", line 304, in analyze
    print(f"Alpha-i-metric: {compute_alpha_i_metric_parallel(g, distance_matrix)}")
  File "main.py", line 161, in compute_alpha_i_metric_parallel
    if isinstance(e, multiprocessing.BrokenProcessPool):
AttributeError: module 'multiprocessing' has no attribute 'BrokenProcessPool'
+ echo Completed
slurmstepd: error: Detected 19 oom_kill events in StepId=30791565.batch. Some of the step tasks have been OOM Killed.
